"use client";

import { brand } from "@nutrition-platform/brand";
import { useState } from "react";
import {
  Activity, AlertCircle, ArrowLeft, ArrowRight, BarChart3, Bell, BookOpen, CalendarDays,
  Camera, CircleHelp,
  Check, CheckCircle2, ChevronDown, ChevronRight, ClipboardList,
  Clock3, FileText, Heart, Home as HomeIcon, Image as ImageIcon, Instagram,
  LayoutDashboard, Leaf, Menu, MessageSquare, MoreHorizontal,
  Plus, Search, Send, Settings, ShieldCheck, Smartphone, Sparkles, Stethoscope,
  Target, TrendingUp, UserRound, Users, Utensils, WandSparkles, X, Zap,
} from "lucide-react";

type Surface = "nutritionist" | "patient-web" | "patient-mobile" | "landing";
type NutriView = "today" | "patients" | "consultation" | "plan" | "growth";
type PatientStage = "list" | "profile";

const navItems = [
  { id: "today" as const, label: "Hoje", icon: LayoutDashboard },
  { id: "patients" as const, label: "Pacientes", icon: Users },
  { id: "consultation" as const, label: "Consultas", icon: Stethoscope },
  { id: "plan" as const, label: "Planos", icon: ClipboardList },
  { id: "calendar" as const, label: "Agenda", icon: CalendarDays },
  { id: "follow" as const, label: "Acompanhamento", icon: Activity },
  { id: "messages" as const, label: "Mensagens", icon: MessageSquare, badge: "4" },
  { id: "growth" as const, label: "Crescimento", icon: TrendingUp, badge: "Novo" },
  { id: "insights" as const, label: "Insights", icon: BarChart3 },
  { id: "docs" as const, label: "Documentos", icon: FileText },
];

const patients = [
  { name: "Camila Ribeiro", initials: "CR", focus: "Performance e rotina", last: "Hoje, 09:42", next: "Hoje, 14:00", signal: "Atenção", tone: "amber" },
  { name: "Lucas Martins", initials: "LM", focus: "Composição corporal", last: "Ontem, 20:15", next: "22 ago, 10:30", signal: "Em dia", tone: "green" },
  { name: "Renata Alves", initials: "RA", focus: "Saúde intestinal", last: "17 ago, 18:02", next: "25 ago, 16:00", signal: "Em dia", tone: "green" },
  { name: "João Pedro Lima", initials: "JL", focus: "Educação alimentar", last: "15 ago, 12:10", next: "Sem retorno", signal: "Retomar", tone: "gray" },
  { name: "Beatriz Souza", initials: "BS", focus: "Nutrição esportiva", last: "12 ago, 07:21", next: "28 ago, 08:00", signal: "Atenção", tone: "amber" },
];

function PrototypeBar({ surface, onSurface }: { surface: Surface; onSurface: (surface: Surface) => void }) {
  const surfaces: Array<[Surface, string]> = [["nutritionist","Nutricionista web"],["patient-web","Paciente web"],["patient-mobile","Paciente mobile"],["landing","Landing page"]];
  return (
    <div className="prototype-bar">
      <div className="prototype-brand"><span className="prototype-dot" /><strong>Protótipo navegável</strong><span>{brand.name} · identidade de trabalho</span></div>
      <div className="surface-switcher" aria-label="Superfícies do protótipo">
        {surfaces.map(([id,label])=><button key={id} className={`surface-tab ${surface===id?"active":""}`} onClick={()=>onSurface(id)}>{label}</button>)}
      </div>
      <div className="prototype-status"><span /> MVP · fluxo principal</div>
    </div>
  );
}

function LogoMark() { return <span className="logo-mark"><span /></span>; }

function Sidebar({ view, onChange }: { view: NutriView; onChange: (view: NutriView) => void }) {
  return (
    <aside className="sidebar">
      <div className="product-logo"><LogoMark /><span>{brand.name}</span></div>
      <nav className="sidebar-nav" aria-label="Navegação principal">
        {navItems.map((item) => {
          const isClickable = ["today", "patients", "consultation", "plan", "growth"].includes(item.id);
          const active = item.id === view;
          return <button key={item.id} className={`nav-item ${active ? "active" : ""}`} onClick={() => isClickable && onChange(item.id as NutriView)} aria-current={active ? "page" : undefined}>
            <item.icon size={18} strokeWidth={1.8} /><span>{item.label}</span>
            {item.badge && <small className={item.badge === "Novo" ? "new-badge" : "count-badge"}>{item.badge}</small>}
          </button>;
        })}
      </nav>
      <div className="sidebar-foot">
        <button className="nav-item"><Settings size={18} /><span>Configurações</span></button>
        <div className="account-card"><div className="avatar avatar-dark">MC</div><div><strong>Mariana Costa</strong><span>Nutricionista</span></div><MoreHorizontal size={18} /></div>
      </div>
    </aside>
  );
}

function Topbar({ title, subtitle, onAddPatient }: { title: string; subtitle?: string; onAddPatient: () => void }) {
  return (
    <header className="topbar">
      <div className="page-title"><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>
      <div className="top-actions">
        <label className="global-search"><Search size={17} /><input aria-label="Busca global" placeholder="Buscar paciente, plano ou ação..." /><kbd>⌘ K</kbd></label>
        <button className="icon-button" aria-label="Notificações"><Bell size={19} /><span className="notification-dot" /></button>
        <button className="button secondary" onClick={onAddPatient}><Plus size={17} />Novo paciente</button>
      </div>
    </header>
  );
}

function Metric({ label, value, detail, icon: Icon, accent }: { label: string; value: string; detail: string; icon: typeof Users; accent: string }) {
  return <article className="metric-card"><div className={`metric-icon ${accent}`}><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>;
}

function TodayView({ onPrepare, onPatient, onPlan, onGrowth }: { onPrepare: () => void; onPatient: () => void; onPlan: () => void; onGrowth: () => void }) {
  return (
    <div className="content-stack">
      <section className="welcome-row">
        <div><p className="eyebrow">Quarta-feira, 19 de agosto</p><h2>Bom dia, Mariana.</h2><p>Você tem 4 consultas e 6 ações importantes para hoje.</p></div>
        <div className="day-progress"><span>Seu dia</span><strong>3 de 9 ações concluídas</strong><div><i style={{width:"34%"}} /></div></div>
      </section>
      <section className="metrics-grid">
        <Metric label="Pacientes ativos" value="84" detail="+6 neste mês" icon={Users} accent="teal" />
        <Metric label="Consultas na semana" value="18" detail="4 restantes hoje" icon={CalendarDays} accent="blue" />
        <Metric label="Planos para revisar" value="3" detail="1 com prazo hoje" icon={ClipboardList} accent="orange" />
        <Metric label="Retorno de pacientes" value="72%" detail="+8% nos últimos 30 dias" icon={TrendingUp} accent="violet" />
      </section>
      <section className="dashboard-grid">
        <div className="main-column">
          <article className="panel next-consultation">
            <div className="panel-head"><div><p className="eyebrow">Próxima consulta · 14:00</p><h3>Camila Ribeiro</h3></div><button className="text-button" onClick={onPatient}>Abrir paciente <ChevronRight size={16} /></button></div>
            <div className="patient-summary-row"><div className="avatar avatar-coral">CR</div><div><strong>Performance e rotina</strong><span>Última consulta há 28 dias</span></div><span className="status-pill warning"><AlertCircle size={14} />2 pontos de atenção</span></div>
            <div className="ai-brief">
              <div className="ai-label"><Sparkles size={16} /><strong>Resumo pré-consulta</strong><span>Gerado por IA · revisar</span></div>
              <p>Camila relatou dificuldade em seguir o lanche da tarde em 3 dias da última semana e substituiu o iogurte com frequência. A energia nos treinos melhorou, mas há uma nova dúvida sobre refeições antes da corrida.</p>
              <div className="brief-points"><span><CheckCircle2 size={15} />Check-in respondido</span><span><Activity size={15} />Peso estável</span><span><MessageSquare size={15} />1 pergunta pendente</span></div>
            </div>
            <div className="panel-actions"><button className="button primary" onClick={onPrepare}><Stethoscope size={17} />Preparar consulta</button><button className="button ghost" onClick={onPlan}>Ver plano atual</button></div>
          </article>
          <article className="panel">
            <div className="panel-head"><div><p className="eyebrow">Agenda</p><h3>Hoje</h3></div><button className="text-button">Ver agenda completa <ChevronRight size={16} /></button></div>
            <div className="timeline-list">
              {[["09:00", "Lucas Martins", "Retorno · concluída", "done"],["11:30", "Renata Alves", "Primeira consulta · concluída", "done"],["14:00", "Camila Ribeiro", "Retorno · anamnese pronta", "current"],["16:30", "Beatriz Souza", "Retorno · aguardando check-in", "next"]].map(([time, name, desc, state]) => <div className={`timeline-item ${state}`} key={time}><time>{time}</time><i /><div><strong>{name}</strong><span>{desc}</span></div>{state === "current" && <button onClick={onPrepare}>Preparar</button>}</div>)}
            </div>
          </article>
        </div>
        <div className="side-column">
          <article className="panel attention-panel">
            <div className="panel-head"><div><p className="eyebrow">Acompanhamento</p><h3>Precisam de atenção</h3></div><span className="number-badge">4</span></div>
            {[["Beatriz Souza", "Não respondeu ao check-in", "2 dias"],["João Pedro Lima", "Retorno ainda não agendado", "6 dias"],["Camila Ribeiro", "3 substituições na semana", "Hoje"]].map(([name, reason, when], i) => <button className="attention-row" key={name} onClick={i === 2 ? onPatient : undefined}><div className="avatar avatar-small">{name.split(" ").map(x=>x[0]).join("")}</div><div><strong>{name}</strong><span>{reason}</span></div><small>{when}</small></button>)}
            <button className="full-link">Abrir acompanhamento <ChevronRight size={16} /></button>
          </article>
          <article className="panel task-panel"><div className="panel-head"><div><p className="eyebrow">Foco de hoje</p><h3>Próximas ações</h3></div></div>{["Revisar plano de Lucas", "Responder 4 mensagens", "Confirmar consulta de Beatriz"].map((task, i) => <label className="task-row" key={task}><input type="checkbox" defaultChecked={i === 2} /><span>{task}</span><small>{i === 0 ? "12:00" : i === 1 ? "Hoje" : "Feito"}</small></label>)}</article>
          <article className="panel growth-mini" onClick={onGrowth} role="button" tabIndex={0}><div className="growth-icon"><Target size={20} /></div><div><span>Ritual de crescimento</span><strong>Planeje a próxima semana</strong><small>3 ideias salvas · 2 leads para retornar</small></div><ChevronRight size={18} /></article>
        </div>
      </section>
    </div>
  );
}

function PatientsView({ stage, onStage, onPlan }: { stage: PatientStage; onStage: (s: PatientStage) => void; onPlan: () => void }) {
  if (stage === "profile") return <PatientProfile onBack={() => onStage("list")} onPlan={onPlan} />;
  return <div className="content-stack">
    <section className="section-heading"><div><p className="eyebrow">84 pacientes ativos</p><h2>Pacientes</h2><p>Encontre rapidamente quem precisa de cuidado agora.</p></div><button className="button primary"><Plus size={17} />Adicionar paciente</button></section>
    <article className="panel data-panel"><div className="table-tools"><label className="table-search"><Search size={17} /><input placeholder="Buscar por nome, objetivo ou contato" /></label><button className="filter-button">Todos os pacientes <ChevronDown size={15} /></button><button className="filter-button">Atenção primeiro <ChevronDown size={15} /></button></div>
      <div className="patient-table" role="table"><div className="table-row table-header" role="row"><span>Paciente</span><span>Foco do cuidado</span><span>Última atividade</span><span>Próximo encontro</span><span>Sinal</span><span /></div>{patients.map((patient, index) => <button className="table-row" role="row" key={patient.name} onClick={() => index === 0 && onStage("profile")}><span className="patient-cell"><i className={`avatar ${index === 0 ? "avatar-coral" : ""}`}>{patient.initials}</i><span><strong>{patient.name}</strong><small>{index === 0 ? "camila.ribeiro@email.com" : "Paciente ativo"}</small></span></span><span>{patient.focus}</span><span>{patient.last}</span><span>{patient.next}</span><span><i className={`status-pill ${patient.tone}`}>{patient.signal}</i></span><span><ChevronRight size={17} /></span></button>)}</div>
    </article>
  </div>;
}

function PatientProfile({ onBack, onPlan }: { onBack: () => void; onPlan: () => void }) {
  return <div className="content-stack">
    <button className="back-button" onClick={onBack}><ArrowLeft size={17} />Todos os pacientes</button>
    <section className="patient-hero"><div className="avatar avatar-large avatar-coral">CR</div><div className="patient-identity"><div><h2>Camila Ribeiro</h2><span className="status-pill green"><CheckCircle2 size={14} />Ativa</span></div><p>Performance e rotina · acompanhamento desde março de 2026</p></div><div className="patient-hero-actions"><button className="button secondary"><MessageSquare size={17} />Mensagem</button><button className="button primary"><Stethoscope size={17} />Iniciar consulta</button></div></section>
    <div className="profile-tabs">{["Visão geral","Histórico","Avaliações","Medidas e evolução","Objetivos","Planos","Acompanhamento","Documentos"].map((t,i)=><button className={i===0?"active":""} key={t}>{t}</button>)}</div>
    <section className="profile-grid"><div className="main-column">
      <article className="panel clinical-summary"><div className="panel-head"><div><p className="eyebrow">Resumo do cuidado</p><h3>O que importa agora</h3></div><span className="ai-soft"><Sparkles size={14} />Resumo assistido por IA</span></div><div className="summary-grid"><div><span>Objetivo atual</span><strong>Melhorar energia e recuperação nos treinos</strong></div><div><span>Restrições</span><strong>Sem alergias relatadas</strong></div><div><span>Próxima consulta</span><strong>Hoje, 14:00</strong></div><div><span>Plano atual</span><strong>Versão 1 · publicado em 22 jul</strong></div></div><p className="summary-note">Camila mantém boa consistência nas refeições principais. O lanche da tarde segue como principal ponto de adaptação devido à rotina de trabalho. Há uma pergunta nova sobre pré-treino para corrida.</p></article>
      <article className="panel"><div className="panel-head"><div><p className="eyebrow">Linha do tempo</p><h3>Atividade recente</h3></div><button className="text-button">Ver histórico</button></div><div className="activity-feed"><div><i className="feed-icon ai"><Sparkles size={15} /></i><span><strong>Check-in semanal respondido</strong><small>Energia melhorou; relatou dificuldade no lanche da tarde.</small></span><time>Ontem</time></div><div><i className="feed-icon meal"><Utensils size={15} /></i><span><strong>Substituição registrada</strong><small>Iogurte natural por queijo minas + fruta.</small></span><time>17 ago</time></div><div><i className="feed-icon message"><MessageSquare size={15} /></i><span><strong>Nova pergunta</strong><small>“O que devo comer antes do treino longo?”</small></span><time>16 ago</time></div></div></article>
    </div><div className="side-column">
      <article className="panel plan-card"><div className="panel-head"><div><p className="eyebrow">Plano atual</p><h3>Performance · rotina semanal</h3></div><span className="status-pill green">Publicado</span></div><div className="plan-stat-row"><span><strong>5</strong>refeições/dia</span><span><strong>9</strong>substituições</span><span><strong>22 jul</strong>publicado</span></div><button className="button primary full" onClick={onPlan}>Abrir e revisar plano <ChevronRight size={17} /></button></article>
      <article className="panel"><div className="panel-head"><div><p className="eyebrow">Pontos de atenção</p><h3>Esta semana</h3></div></div><div className="attention-note"><AlertCircle size={17} /><div><strong>Lanche da tarde</strong><p>3 substituições em 5 dias. Vale revisar praticidade e disponibilidade.</p></div></div><div className="attention-note neutral"><Clock3 size={17} /><div><strong>Check-in concluído</strong><p>Respondido dentro do prazo, com uma dúvida para hoje.</p></div></div></article>
    </div></section>
  </div>;
}

function ConsultationView({ onPlan }: { onPlan: () => void }) {
  const [structured, setStructured] = useState(false);
  return <div className="content-stack consultation-view">
    <section className="consultation-bar"><div><span className="live-dot" />Consulta em andamento</div><span>Camila Ribeiro · retorno</span><small>Salvo agora</small><button className="button secondary">Finalizar depois</button><button className="button primary" onClick={onPlan}>Finalizar e criar plano</button></section>
    <section className="consultation-layout"><aside className="consult-side panel"><div className="patient-mini"><div className="avatar avatar-coral">CR</div><div><strong>Camila Ribeiro</strong><span>28 anos · acompanhamento</span></div></div>{["Resumo pré-consulta","Evolução","Anamnese","Plano atual","Documentos"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}<ChevronRight size={15}/></button>)}<div className="privacy-cue"><ShieldCheck size={17}/><span>Acesso clínico registrado</span></div></aside>
      <main className="consult-main"><article className="panel ai-brief expanded"><div className="ai-label"><Sparkles size={17}/><strong>Resumo pré-consulta</strong><span>Gerado por IA · 4 fontes</span></div><h3>O que mudou desde a última consulta</h3><ul><li>Energia percebida nos treinos passou de 6/10 para 8/10.</li><li>Lanche da tarde foi substituído em três dias por falta de praticidade.</li><li>Peso permaneceu estável; não é o objetivo principal deste ciclo.</li><li>Nova dúvida registrada sobre alimentação antes de treinos longos.</li></ul><button className="text-button">Ver evidências utilizadas <ChevronDown size={15}/></button></article>
        <article className="panel note-editor"><div className="editor-head"><div><p className="eyebrow">Registro da consulta</p><h3>Anotações e conduta</h3></div><span>Rascunho</span></div><textarea value={structured ? "Evolução: paciente relata melhora da energia durante os treinos.\n\nDesafio atual: baixa praticidade do lanche da tarde em dias presenciais.\n\nConduta proposta: revisar opções portáteis e incluir orientação para pré-treino longo." : "Camila relata que sentiu mais energia nos treinos. Nos dias presenciais não conseguiu levar o iogurte e acabou adaptando. Quer opções fáceis para antes da corrida longa..."} readOnly aria-label="Anotações da consulta"/><div className="editor-actions"><button className="ai-action" onClick={()=>setStructured(true)}><Sparkles size={16}/>{structured?"Estrutura aplicada":"Estruturar com IA"}</button><span>A IA cria um rascunho. Você revisa antes de finalizar.</span></div></article>
      </main><aside className="consult-context"><article className="panel"><p className="eyebrow">Perguntas sugeridas</p><h3>Para aprofundar</h3>{["Em quais dias o lanche ficou mais difícil?","Quanto tempo há entre o lanche e o treino?","Que alimentos consegue manter no trabalho?"].map(q=><button className="question-card" key={q}>{q}<Plus size={15}/></button>)}</article><article className="panel"><p className="eyebrow">Dados rápidos</p><div className="quick-data"><span><small>Último peso</small><strong>63,8 kg</strong></span><span><small>Energia</small><strong>8/10</strong></span><span><small>Check-in</small><strong>Respondido</strong></span></div></article></aside></section>
  </div>;
}

function PlanBuilder({ onPublish }: { onPublish: () => void }) {
  const [aiOpen, setAiOpen] = useState(false); const [accepted, setAccepted] = useState(false);
  const meals = [["07:30", "Café da manhã", "Pão francês, ovos mexidos, mamão", "402 kcal"],["10:30", "Lanche", "Iogurte natural, banana e aveia", "286 kcal"],["13:00", "Almoço", "Arroz, feijão, frango e legumes", "612 kcal"],["16:30", "Lanche da tarde", accepted ? "Queijo minas, fruta e castanhas" : "Iogurte, fruta e aveia", "318 kcal"],["20:00", "Jantar", "Mandioca, patinho moído e salada", "544 kcal"]];
  return <div className="plan-builder"><div className="builder-top"><div><button className="back-button"><ArrowLeft size={17}/>Camila Ribeiro</button><h2>Plano alimentar · versão 2</h2></div><div className="builder-state"><span className="status-pill gray">Rascunho salvo</span><button className="button secondary">Visualizar como paciente</button><button className="button primary" onClick={onPublish}>Revisar e publicar</button></div></div>
    <div className="builder-layout"><aside className="food-library"><div className="library-head"><h3>Adicionar ao plano</h3><label><Search size={16}/><input placeholder="Buscar alimento ou receita"/></label></div><div className="source-tabs"><button className="active">Alimentos</button><button>Receitas</button><button>Meus itens</button></div>{["Banana-prata, crua","Pão francês","Ovo de galinha, inteiro","Queijo minas frescal","Iogurte natural integral"].map((f,i)=><button className="food-row" key={f}><div><strong>{f}</strong><span>{i%2===0?"TACO":"TBCA"} · por 100 g</span></div><Plus size={16}/></button>)}</aside>
      <main className="meal-canvas"><div className="constraint-strip"><span><Target size={16}/><strong>Objetivo:</strong> energia e recuperação</span><span><ShieldCheck size={16}/><strong>Restrições:</strong> nenhuma relatada</span><button>Ver contexto completo</button></div><div className="day-selector"><button><ChevronDown size={15}/>Rotina de treino</button><span>2.162 kcal · P 128 g · C 278 g · G 62 g</span></div><div className="meal-list">{meals.map(([time,name,foods,kcal],i)=><article className={`meal-card ${i===3?"selected":""}`} key={name}><time>{time}</time><div className="meal-index">{i+1}</div><div><strong>{name}</strong><p>{foods}</p><small>{i===3?"2 alternativas aprovadas":"Clique para editar alimentos e porções"}</small></div><span>{kcal}</span>{i===3&&<button className="ai-action compact" onClick={()=>setAiOpen(true)}><Sparkles size={15}/>Sugerir opções</button>}<button className="icon-button bare"><MoreHorizontal size={17}/></button></article>)}</div><button className="add-meal"><Plus size={17}/>Adicionar refeição</button></main>
      <aside className="nutrition-summary"><p className="eyebrow">Resumo nutricional</p><h3>Totais do dia</h3><div className="calorie-ring"><div><strong>2.162</strong><span>kcal</span></div></div><div className="macro-bars"><div><span>Proteínas <strong>128 g</strong></span><i><b style={{width:"78%"}}/></i></div><div><span>Carboidratos <strong>278 g</strong></span><i><b style={{width:"86%"}}/></i></div><div><span>Gorduras <strong>62 g</strong></span><i><b style={{width:"64%"}}/></i></div></div><button className="full-link">Ver micronutrientes <ChevronRight size={16}/></button><div className="version-note"><Clock3 size={16}/><span><strong>Comparando com a versão 1</strong>+124 kcal e 3 novas substituições</span></div></aside></div>
    {aiOpen && <div className="drawer-backdrop" onClick={()=>setAiOpen(false)}><aside className="ai-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="metric-icon violet"><Sparkles size={18}/></span><div><small>Assistência contextual</small><h3>Alternativas para o lanche</h3></div></div><button className="icon-button bare" onClick={()=>setAiOpen(false)}><X size={20}/></button></div><div className="ai-context"><strong>Considerando</strong><span>Praticidade · trabalho presencial · treino às 18:30 · porção equivalente</span></div>{[["Queijo minas + fruta + castanhas","1 fatia média (40 g) · 1 banana-prata · 10 g castanhas","312 kcal"],["Sanduíche de frango desfiado","2 fatias de pão integral · 60 g de frango","326 kcal"],["Tapioca com ovo","50 g de goma · 1 ovo · 1 fruta pequena","304 kcal"]].map((x,i)=><div className={`suggestion-card ${accepted&&i===0?"accepted":""}`} key={x[0]}><div><strong>{x[0]}</strong><span>{x[1]}</span><small>{x[2]} · estimativa com fonte TBCA/TACO</small></div>{accepted&&i===0?<span className="status-pill green"><Check size={14}/>Aceita</span>:<button className="button secondary" onClick={()=>{setAccepted(true);setTimeout(()=>setAiOpen(false),500)}}>Usar opção</button>}</div>)}<div className="ai-disclaimer"><ShieldCheck size={17}/><p>Conteúdo gerado por IA. Revise porções, fontes e adequação clínica antes de publicar.</p></div></aside></div>}
  </div>;
}

function GrowthView() {
  const [generated, setGenerated] = useState(false);
  return <div className="content-stack"><section className="section-heading"><div><p className="eyebrow">Crescimento ético</p><h2>Planeje sua presença profissional</h2><p>Conteúdo, contatos e acompanhamento comercial no ritmo da sua prática.</p></div><button className="button primary" onClick={()=>setGenerated(true)}><Sparkles size={17}/>Planejar com IA</button></section>
    <section className="growth-overview"><article className="panel ritual-card"><div><span className="metric-icon orange"><Target size={20}/></span><div><p className="eyebrow">Ritual da semana</p><h3>Transformar dúvidas reais em conteúdo útil</h3><p>Você tem 5 perguntas frequentes dos pacientes que podem virar conteúdos educativos.</p></div></div><button className="button secondary" onClick={()=>setGenerated(true)}>Montar a semana</button></article><Metric label="Leads qualificados" value="7" detail="3 aguardam retorno" icon={Users} accent="teal"/><Metric label="Conteúdos planejados" value={generated?"6":"3"} detail={generated?"Semana organizada":"2 ainda em rascunho"} icon={FileText} accent="violet"/></section>
    <section className="growth-grid"><article className="panel content-pipeline"><div className="panel-head"><div><p className="eyebrow">Calendário editorial</p><h3>Semana de 24 a 30 de agosto</h3></div><button className="filter-button">Instagram <ChevronDown size={15}/></button></div><div className="week-grid">{["Seg 24","Ter 25","Qua 26","Qui 27","Sex 28"].map((day,i)=><div className="day-column" key={day}><strong>{day}</strong>{(generated||i<3)&&<div className={`content-chip c${i}`}><span>{["Carrossel","Story","Reel","Carrossel","Story"][i]}</span><p>{["Como adaptar o lanche na rotina","Bastidores: preparo de consulta","3 erros ao copiar dietas da internet","O que observar antes do treino","Caixa de perguntas"][i]}</p><small>{i===0?"Em revisão ética":"Rascunho"}</small></div>}<button><Plus size={15}/>Adicionar</button></div>)}</div></article><article className="panel lead-pipeline"><div className="panel-head"><div><p className="eyebrow">Novos pacientes</p><h3>Próximos contatos</h3></div><span className="number-badge">3</span></div>{[["Fernanda Rocha","Instagram · objetivo: corrida","Responder hoje"],["Rafael Nunes","Indicação · saúde intestinal","Aguardando agenda"],["Paula Lima","Perfil profissional · primeira consulta","Novo"]].map(x=><div className="lead-row" key={x[0]}><div className="avatar avatar-small">{x[0].split(" ").map(y=>y[0]).join("")}</div><div><strong>{x[0]}</strong><span>{x[1]}</span></div><small>{x[2]}</small><ChevronRight size={16}/></div>)}<button className="full-link">Abrir pipeline de leads <ChevronRight size={16}/></button></article></section>
    <div className="ethics-banner"><ShieldCheck size={20}/><div><strong>Conteúdo com revisão profissional</strong><p>A IA ajuda a estruturar ideias. Nada é publicado automaticamente; alegações, fontes e linguagem ficam sob seu controle.</p></div><button>Ver regras</button></div>
  </div>;
}

type PatientView = "today" | "plan" | "progress" | "messages";

function PatientWeb() {
  const [view, setView] = useState<PatientView>("today");
  const [swapOpen, setSwapOpen] = useState(false);
  const [swapped, setSwapped] = useState(false);
  const [checkIn, setCheckIn] = useState(false);
  const nav: Array<[PatientView,string,typeof HomeIcon]> = [["today","Hoje",HomeIcon],["plan","Meu plano",Utensils],["progress","Evolução",TrendingUp],["messages","Mensagens",MessageSquare]];
  return <section className="patient-web-app">
    <header className="patient-web-header"><div className="patient-brand"><LogoMark/><strong>{brand.name}</strong><span>{brand.promise}</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon size={17}/>{label}{id==="messages"&&<i/>}</button>)}</nav><div className="patient-user"><button aria-label="Ajuda"><CircleHelp size={18}/></button><button aria-label="Notificações"><Bell size={18}/></button><div className="avatar avatar-coral">CR</div><span>Camila Ribeiro<small>Plano ativo</small></span><ChevronDown size={15}/></div></header>
    <main className="patient-web-content">
      {view==="today"&&<div className="patient-home-grid"><div className="patient-primary">
        <section className="patient-welcome"><div><p className="eyebrow">Quarta-feira, 19 de agosto</p><h1>Bom dia, Camila 👋</h1><p>Seu plano cabe na sua rotina. Vamos por uma refeição de cada vez.</p></div><div className="adherence-score"><span>Esta semana</span><strong>82%</strong><small>de refeições acompanhadas</small></div></section>
        <article className="patient-next-card"><div className="next-card-top"><span><Clock3 size={15}/>Próxima refeição · 16:30</span><i>em 1h20</i></div><div className="next-meal-content"><div className="meal-photo-placeholder"><Utensils size={28}/></div><div><p className="eyebrow">Lanche da tarde</p><h2>{swapped?"Queijo minas, fruta e castanhas":"Iogurte, fruta e aveia"}</h2><p>{swapped?"1 fatia média · 1 banana-prata · 10 g castanhas":"1 pote natural · 1 banana-prata · 2 colheres de aveia"}</p><div className="meal-tags"><span>≈ {swapped?"312":"318"} kcal</span><span>Opções aprovadas pela Mariana</span></div></div></div><div className="next-card-actions"><button className="button secondary" onClick={()=>setSwapOpen(true)}><WandSparkles size={16}/>Ver substituições</button><button className="button primary" onClick={()=>setCheckIn(true)}><Check size={16}/>{checkIn?"Refeição registrada":"Registrar refeição"}</button></div></article>
        <section className="today-meals"><div className="patient-section-head"><div><p className="eyebrow">Seu dia</p><h2>Refeições de hoje</h2></div><button onClick={()=>setView("plan")}>Ver plano completo <ArrowRight size={16}/></button></div>{[["07:30","Café da manhã","Pão, ovos e mamão","done"],["10:30","Lanche","Iogurte, banana e aveia","done"],["13:00","Almoço","Arroz, feijão, frango e legumes","done"],["16:30","Lanche da tarde",swapped?"Queijo minas, fruta e castanhas":"Iogurte, fruta e aveia","current"],["20:00","Jantar","Mandioca, patinho e salada","next"]].map(([time,name,foods,state])=><button className={`patient-meal-row ${state}`} key={time} onClick={()=>state==="current"&&setSwapOpen(true)}><time>{time}</time><i>{state==="done"?<Check size={14}/>:<Utensils size={14}/>}</i><span><strong>{name}</strong><small>{foods}</small></span><em>{state==="done"?"Registrada":state==="current"?"Agora":"Mais tarde"}</em><ChevronRight size={17}/></button>)}</section>
      </div><aside className="patient-aside"><article className="care-card"><div className="care-person"><div className="care-avatar">MC</div><span><small>Sua nutricionista</small><strong>Mariana Costa</strong><em>CRN-3 00000</em></span></div><p>“Camila, foque na praticidade hoje. Suas opções de lanche já estão ajustadas.”</p><button className="button secondary full" onClick={()=>setView("messages")}><MessageSquare size={16}/>Enviar mensagem</button></article><article className="weekly-checkin"><span className="metric-icon violet"><Heart size={19}/></span><div><p className="eyebrow">Check-in semanal</p><h3>Como foi sua semana?</h3><p>Leva menos de 2 minutos e ajuda a Mariana a acompanhar você.</p></div><button className="button primary full" onClick={()=>setCheckIn(true)}>{checkIn?"Check-in enviado":"Responder agora"}</button></article><article className="patient-tip"><Zap size={18}/><div><strong>Antes do treino longo</strong><p>Mariana adicionou uma orientação nova ao seu plano.</p></div><button onClick={()=>setView("plan")}>Abrir</button></article></aside></div>}
      {view==="plan"&&<PatientPlan onSwap={()=>setSwapOpen(true)} swapped={swapped}/>}
      {view==="progress"&&<PatientProgress/>}
      {view==="messages"&&<PatientMessages/>}
    </main>
    {swapOpen&&<div className="patient-sheet-backdrop" onClick={()=>setSwapOpen(false)}><aside className="patient-swap-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="patient-section-head"><div><p className="eyebrow">Trocas seguras</p><h2>Escolha outra opção</h2><p>Somente alternativas aprovadas por Mariana para esta refeição.</p></div><button className="icon-button bare" onClick={()=>setSwapOpen(false)}><X/></button></div><div className="original-meal"><span>Opção atual</span><strong>{swapped?"Queijo minas, fruta e castanhas":"Iogurte, fruta e aveia"}</strong><small>≈ {swapped?"312":"318"} kcal</small></div>{[["Queijo minas, fruta e castanhas","Boa para levar ao trabalho","≈ 312 kcal"],["Sanduíche de frango desfiado","Opção salgada e prática","≈ 326 kcal"],["Tapioca com ovo e uma fruta","Melhor para quando estiver em casa","≈ 304 kcal"]].map((x,i)=><button className={`patient-swap-option ${swapped&&i===0?"selected":""}`} key={x[0]} onClick={()=>{setSwapped(i===0);setSwapOpen(false)}}><i>{i+1}</i><span><strong>{x[0]}</strong><small>{x[1]}</small></span><em>{x[2]}</em><ChevronRight size={17}/></button>)}<div className="professional-control"><ShieldCheck size={17}/><p>Estas opções fazem parte do seu plano. Para outras mudanças, converse com Mariana.</p></div></aside></div>}
  </section>;
}

function PatientPlan({onSwap,swapped}:{onSwap:()=>void;swapped:boolean}) {
  const [day,setDay]=useState("Treino");
  return <div className="patient-page"><section className="patient-page-title"><div><p className="eyebrow">Plano publicado em 18 ago</p><h1>Meu plano alimentar</h1><p>Versão 2 · personalizada por Mariana Costa</p></div><span className="plan-valid"><ShieldCheck size={17}/>Plano ativo</span></section><div className="patient-day-tabs">{["Treino","Descanso","Fim de semana"].map(x=><button key={x} className={day===x?"active":""} onClick={()=>setDay(x)}>{x}</button>)}</div><div className="patient-plan-layout"><section className="patient-plan-list">{[["07:30","Café da manhã","Pão francês, ovos mexidos e mamão","402 kcal"],["10:30","Lanche","Iogurte natural, banana e aveia","286 kcal"],["13:00","Almoço","Arroz, feijão, frango e legumes","612 kcal"],["16:30","Lanche da tarde",swapped?"Queijo minas, fruta e castanhas":"Iogurte, fruta e aveia","318 kcal"],["20:00","Jantar","Mandioca, patinho moído e salada","544 kcal"]].map((x,i)=><article className="patient-plan-meal" key={x[0]}><time>{x[0]}</time><div className={`patient-meal-icon m${i}`}><Utensils size={18}/></div><div><small>Refeição {i+1}</small><h3>{x[1]}</h3><p>{x[2]}</p></div><span>{x[3]}</span>{i===3?<button onClick={onSwap}><WandSparkles size={15}/>Substituir</button>:<button><ChevronDown size={16}/></button>}</article>)}</section><aside className="plan-guidance"><div className="guidance-hero"><BookOpen size={23}/><div><small>Orientação da Mariana</small><h3>Pré-treino para corrida longa</h3></div></div><p>Nos treinos acima de 60 minutos, priorize a opção sinalizada e respeite o intervalo combinado na consulta.</p><button>Ler orientação completa <ArrowRight size={15}/></button><hr/><span><ShieldCheck size={17}/><p>Alterações no plano ficam registradas e são visíveis para sua nutricionista.</p></span></aside></div></div>;
}

function PatientProgress() {
  return <div className="patient-page"><section className="patient-page-title"><div><p className="eyebrow">Sua jornada</p><h1>Evolução sem pressão</h1><p>Veja mudanças importantes além do peso.</p></div><button className="button primary"><Plus size={16}/>Novo registro</button></section><div className="progress-summary"><article><span className="metric-icon teal"><Zap/></span><div><small>Energia nos treinos</small><strong>8/10</strong><em>+2 desde julho</em></div></article><article><span className="metric-icon orange"><Heart/></span><div><small>Bem-estar</small><strong>Bom</strong><em>Estável esta semana</em></div></article><article><span className="metric-icon violet"><CheckCircle2/></span><div><small>Consistência</small><strong>82%</strong><em>+9% em 30 dias</em></div></article></div><div className="progress-layout"><article className="progress-chart-card"><div className="patient-section-head"><div><p className="eyebrow">Energia percebida</p><h2>Últimos 8 check-ins</h2></div><button>3 meses <ChevronDown size={15}/></button></div><div className="simple-chart">{[5,6,6,7,6,8,7,8].map((h,i)=><div key={i}><span style={{height:`${h*10}%`}}/><small>{i%2===0?`${i+1} ago`:""}</small></div>)}</div><p className="chart-insight"><Sparkles size={16}/><span><strong>Padrão positivo</strong>Sua energia melhorou nas semanas com maior consistência no lanche da tarde.</span></p></article><aside className="progress-moments"><p className="eyebrow">Marcos recentes</p><h2>O que mudou</h2>{[["Hoje","Energia 8/10","Melhor resultado do ciclo"],["12 ago","Treino longo concluído","Sem desconforto relatado"],["29 jul","Plano ajustado","Mais praticidade à tarde"]].map(x=><div key={x[0]}><time>{x[0]}</time><i/><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</aside></div></div>;
}

function PatientMessages() {
  const [sent,setSent]=useState(false);
  return <div className="patient-page messages-page"><section className="patient-page-title"><div><p className="eyebrow">Canal de cuidado</p><h1>Mensagens</h1><p>Dúvidas sobre o seu plano ficam organizadas aqui.</p></div></section><div className="message-layout"><aside className="conversation-list"><label><Search size={16}/><input placeholder="Buscar conversa"/></label><button className="active"><div className="care-avatar small">MC</div><span><strong>Mariana Costa</strong><small>Nutricionista · online hoje</small></span><i>1</i></button></aside><section className="chat-panel"><header><div className="care-avatar small">MC</div><span><strong>Mariana Costa</strong><small>Responde em horário comercial</small></span><button><CircleHelp size={18}/></button></header><div className="chat-messages"><div className="chat-date">Hoje</div><div className="bubble received">Oi, Camila! Já deixei três opções mais práticas no seu lanche da tarde. Teste a que fizer mais sentido hoje.<small>12:18</small></div><div className="bubble sent">Ótimo! Posso usar a opção com queijo antes do treino?<small>12:24</small></div><div className="bubble received">Pode sim. Para o treino de hoje ela está dentro do intervalo e das porções que combinamos.<small>12:31</small></div>{sent&&<div className="bubble sent">Obrigada! Vou registrar como me senti depois do treino.<small>Agora</small></div>}</div><div className="message-suggestions"><span>Respostas rápidas</span><button>Tenho uma dúvida sobre a porção</button><button>Quero contar como foi o treino</button></div><footer><button aria-label="Anexar imagem"><ImageIcon size={18}/></button><input placeholder="Escreva sua mensagem..."/><button className="send-button" onClick={()=>setSent(true)}><Send size={17}/></button></footer></section></div></div>;
}

type MobileView = "today" | "plan" | "assistant" | "progress";

function PatientMobile() {
  const [view,setView]=useState<MobileView>("today"); const [mealDone,setMealDone]=useState(false); const [assistantAnswer,setAssistantAnswer]=useState(false);
  const mobileNav:Array<[MobileView,string,typeof HomeIcon]>=[["today","Hoje",HomeIcon],["plan","Plano",Utensils],["assistant","Assistente",Sparkles],["progress","Evolução",TrendingUp]];
  return <section className="mobile-showcase"><div className="mobile-copy"><p className="eyebrow">Experiência mobile-first</p><h1>O cuidado no bolso,<br/>sem transformar alimentação em cobrança.</h1><p>Um protótipo do futuro aplicativo do paciente, consumindo as mesmas capacidades do backend do produto web.</p><div className="mobile-principles"><span><CheckCircle2/>Plano sempre acessível</span><span><ShieldCheck/>IA limitada pelo profissional</span><span><Heart/>Progresso com contexto</span></div><div className="mobile-note"><Smartphone/><p><strong>Interaja com o aparelho</strong>Use a navegação inferior, registre uma refeição ou peça uma explicação ao assistente.</p></div></div><div className="phone-shell"><div className="phone-speaker"/><div className="phone-screen"><header className="mobile-header"><div><small>Quarta, 19 de agosto</small><strong>{view==="today"?"Olá, Camila":view==="plan"?"Seu plano":view==="assistant"?"Assistente do plano":"Sua evolução"}</strong></div><div className="avatar avatar-coral">CR</div></header><main className="mobile-content">
    {view==="today"&&<><section className="mobile-streak"><div><span>Consistência semanal</span><strong>82%</strong><small>Você está construindo uma boa rotina</small></div><div className="mini-ring">82</div></section><p className="mobile-kicker">AGORA · LANCHE DA TARDE</p><article className="mobile-meal-card"><div className="mobile-meal-art"><Utensils/></div><span className="approved-pill"><ShieldCheck/>Aprovado por Mariana</span><h2>Queijo minas, fruta e castanhas</h2><p>1 fatia média · 1 banana-prata · 10 g de castanhas</p><div><span>≈ 312 kcal</span><button onClick={()=>setView("plan")}>Ver detalhes</button></div><button className={`mobile-main-action ${mealDone?"done":""}`} onClick={()=>setMealDone(true)}>{mealDone?<><CheckCircle2/>Refeição registrada</>:<><Check/>Registrar refeição</>}</button><button className="mobile-swap" onClick={()=>setView("plan")}><WandSparkles/>Ver outras opções aprovadas</button></article><article className="mobile-nutri-note"><div className="care-avatar small">MC</div><span><small>Mariana deixou uma orientação</small><strong>Observe sua energia no treino de hoje.</strong></span><ChevronRight/></article></>}
    {view==="plan"&&<><div className="mobile-day-tabs"><button className="active">Treino</button><button>Descanso</button><button>Fim de semana</button></div><div className="mobile-plan-summary"><small>Meta do plano</small><strong>Energia e recuperação</strong><span>5 refeições · 2.162 kcal estimadas</span></div><div className="mobile-meal-list">{[["07:30","Café da manhã",true],["10:30","Lanche",true],["13:00","Almoço",true],["16:30","Lanche da tarde",mealDone],["20:00","Jantar",false]].map(x=><button key={String(x[0])}><time>{x[0]}</time><i className={x[2]?"done":""}>{x[2]?<Check/>:<Utensils/>}</i><span><strong>{x[1]}</strong><small>{x[2]?"Registrada":"Ver alimentos e opções"}</small></span><ChevronRight/></button>)}</div></>}
    {view==="assistant"&&<><div className="assistant-intro"><span><Sparkles/></span><h2>Dúvidas sobre o seu plano?</h2><p>Eu explico orientações da Mariana e uso apenas opções aprovadas por ela.</p></div><div className="assistant-scope"><ShieldCheck/><span><strong>Proteção ativa</strong>Não faço diagnóstico nem altero seu plano.</span></div><div className="assistant-chat"><div className="assistant-bubble">Como posso ajudar com sua alimentação hoje?</div>{assistantAnswer&&<><div className="assistant-user-bubble">Por que tem um lanche antes do treino?</div><div className="assistant-bubble">No seu plano, esse lanche ajuda a chegar ao treino com energia sem pesar. Mariana escolheu opções práticas e combinou o intervalo na última consulta.<small>Baseado no seu plano · versão 2</small></div></>}</div><div className="assistant-prompts">{["Por que tem um lanche antes do treino?","O que posso levar ao trabalho?","Explique minha porção do jantar"].map(x=><button key={x} onClick={()=>setAssistantAnswer(true)}>{x}<ArrowRight/></button>)}</div></>}
    {view==="progress"&&<><section className="mobile-progress-hero"><span>Energia nos treinos</span><strong>8<small>/10</small></strong><em>+2 desde o início</em><div>{[5,6,6,7,6,8,7,8].map((h,i)=><i key={i} style={{height:`${h*8}px`}}/>)}</div></section><article className="mobile-insight"><Sparkles/><span><small>Insight da semana</small><strong>Seu lanche da tarde aparece nas semanas de maior energia.</strong></span></article><button className="mobile-photo"><Camera/><span><strong>Registrar progresso</strong><small>Foto, medida ou percepção</small></span><Plus/></button></>}
  </main><nav className="mobile-bottom-nav">{mobileNav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span>{label}</span></button>)}</nav></div></div></section>;
}

function LandingPage() {
  const [menuOpen,setMenuOpen]=useState(false); const [leadOpen,setLeadOpen]=useState(false); const [submitted,setSubmitted]=useState(false);
  return <section className="landing-page"><header className="landing-nav"><div className="landing-brand"><LogoMark/><strong>{brand.name}</strong></div><button className="landing-menu" onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button><nav className={menuOpen?"open":""}><a href="#produto">Produto</a><a href="#crescimento">Crescimento</a><a href="#paciente">Experiência do paciente</a><a href="#seguranca">Segurança</a></nav><div className="landing-actions"><button className="button ghost">Entrar</button><button className="button primary" onClick={()=>setLeadOpen(true)}>Quero testar primeiro</button></div></header><main>
    <section className="landing-hero"><div className="hero-copy"><span className="hero-pill"><Sparkles/>Feito com nutricionistas, para a prática real</span><h1>Mais tempo para cuidar.<br/><em>Mais clareza para crescer.</em></h1><p>Organize consultas, crie planos com agilidade, acompanhe cada paciente e fortaleça sua presença profissional — em uma experiência moderna de ponta a ponta.</p><div className="hero-actions"><button className="landing-primary" onClick={()=>setLeadOpen(true)}>Participar do acesso antecipado <ArrowRight/></button><button className="landing-secondary" onClick={()=>document.getElementById("produto")?.scrollIntoView({behavior:"smooth"})}>Conhecer o produto</button></div><small>Sem compromisso · vagas iniciais limitadas · construído no Brasil</small><div className="hero-proof"><div className="avatar-stack"><i>MC</i><i>AL</i><i>RS</i><i>+</i></div><span><strong>Desenhado com profissionais reais</strong>Fluxos validados no dia a dia do consultório</span></div></div><div className="hero-visual"><div className="visual-glow"/><div className="browser-frame"><div className="browser-top"><i/><i/><i/><span>Seu consultório, hoje</span></div><div className="mini-dashboard"><aside><LogoMark/>{[1,2,3,4,5].map(x=><i key={x}/>)}</aside><main><div className="mini-top"><span/><button>+ Novo paciente</button></div><div className="mini-title"><small>QUARTA-FEIRA</small><strong>Bom dia, Mariana.</strong><span/></div><div className="mini-metrics">{["84 pacientes","4 consultas","3 revisões"].map(x=><div key={x}><i/><strong>{x}</strong><span/></div>)}</div><div className="mini-columns"><section><small>PRÓXIMA CONSULTA · 14:00</small><strong>Camila Ribeiro</strong><div className="mini-ai"><Sparkles/><span><b>Resumo pré-consulta</b><i/><i/><i/></span></div><button>Preparar consulta</button></section><aside><small>PRECISAM DE ATENÇÃO</small>{[1,2,3].map(x=><div key={x}><i/><span/></div>)}</aside></div></main></div></div><div className="floating-card fc-one"><Sparkles/><span><small>Copiloto profissional</small><strong>Resumo pronto para revisar</strong></span><CheckCircle2/></div><div className="floating-card fc-two"><TrendingUp/><span><small>Consistência dos pacientes</small><strong>+12% neste mês</strong></span></div></div></section>
    <section className="logo-strip"><p>Uma nova alternativa para profissionais que querem sair de ferramentas antigas sem perder seus pacientes</p><div>{["Consultório","Plano alimentar","Acompanhamento","Conteúdo","Crescimento"].map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div></section>
    <section className="landing-section problem-section" id="produto"><div className="section-intro"><p className="eyebrow">Seu trabalho merece um sistema à altura</p><h2>A prática não deveria parecer uma sequência infinita de tarefas.</h2><p>O produto conecta o antes, o durante e o depois da consulta para reduzir retrabalho sem tirar o nutricionista do controle.</p></div><div className="problem-grid">{[[ClipboardList,"Planos que levam menos tempo","Biblioteca brasileira, modelos reutilizáveis e assistência contextual para acelerar o rascunho."],[Stethoscope,"Consultas com contexto","Histórico, check-ins e mudanças importantes reunidos antes do paciente entrar."],[Activity,"Acompanhamento que sinaliza","Veja quem precisa de atenção sem depender de memória, planilhas ou mensagens espalhadas."],[MessageSquare,"Comunicação organizada","Dúvidas sobre o plano, arquivos e orientações no mesmo ambiente do cuidado."],[WandSparkles,"IA que você aprova","Rascunhos, resumos e sugestões identificados, auditáveis e sempre sob revisão profissional."],[ShieldCheck,"Dados tratados com seriedade","Privacidade, consentimento, acesso por função e rastreabilidade desde a fundação."]].map(([Icon,title,copy],i)=>{const C=Icon as typeof ClipboardList;return <article key={String(title)} className={`problem-card p${i}`}><span><C/></span><h3>{String(title)}</h3><p>{String(copy)}</p><a>Ver como funciona <ArrowRight/></a></article>})}</div></section>
    <section className="growth-story" id="crescimento"><div className="growth-story-visual"><div className="social-canvas"><header><Instagram/><strong>Semana de conteúdo</strong><button>Planejar com IA</button></header><div className="social-week">{["SEG","TER","QUA","QUI","SEX"].map((x,i)=><div key={x}><small>{x}</small>{i<4&&<article className={`social-post sp${i}`}><span>{["CARROSSEL","STORY","REEL","CAIXA"][i]}</span><strong>{["Lanche na rotina","Bastidores reais","3 mitos da internet","Pergunte à nutri"][i]}</strong><em>Revisão ética</em></article>}<button>+</button></div>)}</div></div><div className="lead-float"><span><Users/></span><div><small>Novo contato qualificado</small><strong>Ana veio pelo Instagram</strong><p>Objetivo: corrida de rua</p></div><button><ChevronRight/></button></div></div><div className="growth-story-copy"><p className="eyebrow">Sua carreira também faz parte do cuidado</p><h2>Do conteúdo ao primeiro contato, sem perder sua voz profissional.</h2><p>Muitos nutricionistas não deixam a profissão por falta de competência — deixam porque captar e manter pacientes virou um segundo trabalho. Por isso, crescimento não é um módulo esquecido no menu.</p><ul><li><CheckCircle2/><span><strong>Transforme dúvidas reais em pautas</strong>Ideias de conteúdo baseadas no que seus pacientes realmente perguntam.</span></li><li><CheckCircle2/><span><strong>Planeje a semana em um ritual simples</strong>Calendário editorial, rascunhos e revisão ética no mesmo fluxo.</span></li><li><CheckCircle2/><span><strong>Acompanhe novos contatos</strong>Organize leads, origem e próximo passo sem montar outro CRM.</span></li></ul><button onClick={()=>setLeadOpen(true)}>Quero participar da construção <ArrowRight/></button></div></section>
    <section className="patient-story" id="paciente"><div className="section-intro"><p className="eyebrow">Uma experiência que valoriza sua entrega</p><h2>O paciente percebe cuidado todos os dias — não só na consulta.</h2></div><div className="patient-story-grid"><div className="patient-story-copy">{[[Smartphone,"Plano simples de seguir","Refeições, orientações e porções fáceis de consultar no celular."],[WandSparkles,"Trocas dentro do combinado","O paciente escolhe apenas entre opções aprovadas por você."],[TrendingUp,"Progresso além da balança","Energia, bem-estar, consistência, fotos e medidas com contexto."],[MessageSquare,"Canal conectado ao plano","Menos dúvida solta no WhatsApp e mais histórico útil para o cuidado."]].map(([Icon,title,copy])=>{const C=Icon as typeof Smartphone;return <div key={String(title)}><span><C/></span><p><strong>{String(title)}</strong>{String(copy)}</p></div>})}</div><div className="landing-phones"><div className="landing-phone lp-back"><div className="lp-head"><LogoMark/><div className="avatar avatar-coral">CR</div></div><small>SEU PLANO</small>{[1,2,3,4].map(x=><div className="lp-meal" key={x}><i/><span/></div>)}</div><div className="landing-phone lp-front"><div className="lp-head"><span>9:41</span><div className="avatar avatar-coral">CR</div></div><small>AGORA · 16:30</small><div className="lp-food"><Utensils/></div><h3>Lanche da tarde</h3><p>Queijo minas, fruta e castanhas</p><button><Check/>Registrar refeição</button><div className="lp-nav"><HomeIcon/><Utensils/><Sparkles/><TrendingUp/></div></div></div></div></section>
    <section className="trust-section" id="seguranca"><div><p className="eyebrow">Tecnologia responsável</p><h2>IA como copiloto. O profissional continua no comando.</h2><p>Assistência deve reduzir tarefas repetitivas, não decidir condutas. Cada recurso é desenhado com aprovação humana, rastreabilidade e limites claros.</p><div className="trust-badges"><span><ShieldCheck/>LGPD desde a base</span><span><UserRound/>Permissões por função</span><span><FileText/>Histórico auditável</span></div></div><aside><div className="trust-flow"><span><Sparkles/></span><div><small>A IA prepara</small><strong>Sugestão de substituição</strong></div></div><i/><div className="trust-flow active"><span><Stethoscope/></span><div><small>O nutricionista revisa</small><strong>Ajusta porção e aprova</strong></div><CheckCircle2/></div><i/><div className="trust-flow"><span><Smartphone/></span><div><small>O paciente recebe</small><strong>Opção segura no plano</strong></div></div></aside></section>
    <section className="landing-final"><span className="final-orb"><Leaf/></span><p className="eyebrow">Acesso antecipado</p><h2>Ajude a construir a ferramenta que você gostaria de usar todos os dias.</h2><p>Estamos convidando um pequeno grupo de nutricionistas para testar os primeiros fluxos e influenciar as próximas decisões do produto.</p><button onClick={()=>setLeadOpen(true)}>Quero ser uma das primeiras <ArrowRight/></button><small>Participação sem compromisso. Entraremos em contato antes de qualquer cobrança.</small></section>
  </main><footer className="landing-footer"><div className="landing-brand"><LogoMark/><strong>{brand.name}</strong></div><p>{brand.descriptor} para nutricionistas e pacientes.</p><span>Protótipo conceitual · 2026</span></footer>
  {leadOpen&&<div className="modal-backdrop" onClick={()=>setLeadOpen(false)}><div className="early-modal" onClick={e=>e.stopPropagation()}>{submitted?<div className="lead-success"><span><CheckCircle2/></span><p className="eyebrow">Interesse registrado</p><h2>Você entrou na lista inicial.</h2><p>Este protótipo não envia dados de verdade. Na implementação, o próximo passo será a confirmação por e-mail e o convite para uma conversa de descoberta.</p><button className="button primary" onClick={()=>setLeadOpen(false)}>Continuar explorando</button></div>:<><div className="modal-head"><div><p className="eyebrow">Acesso antecipado</p><h2>Quero testar primeiro</h2><p>Conte-nos o essencial para priorizarmos os convites.</p></div><button className="icon-button bare" onClick={()=>setLeadOpen(false)}><X/></button></div><div className="form-stack"><label>Seu nome<input placeholder="Como podemos chamar você?"/></label><label>E-mail profissional<input type="email" placeholder="voce@consultorio.com.br"/></label><label>Qual ferramenta usa hoje?<select defaultValue="WebDiet"><option>WebDiet</option><option>Dietbox</option><option>Nutrium</option><option>Planilha / documentos</option><option>Outra</option></select></label><label className="check-label"><input type="checkbox" defaultChecked/>Aceito receber novidades sobre o acesso antecipado.</label></div><div className="modal-actions"><button className="button ghost" onClick={()=>setLeadOpen(false)}>Agora não</button><button className="button primary" onClick={()=>setSubmitted(true)}>Entrar na lista <ArrowRight/></button></div></>}</div></div>}
  </section>;
}

function InviteModal({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(1);
  return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Novo paciente</p><h2>{step===1?"Dados essenciais":"Revisar convite"}</h2></div><button className="icon-button bare" onClick={onClose}><X size={20}/></button></div>{step===1?<div className="form-stack"><label>Nome completo<input defaultValue="Camila Ribeiro" /></label><div className="form-grid"><label>E-mail<input defaultValue="camila.ribeiro@email.com" /></label><label>WhatsApp<input defaultValue="(48) 99999-0000" /></label></div><label>Foco inicial<select defaultValue="Performance e rotina"><option>Performance e rotina</option><option>Saúde clínica</option><option>Educação alimentar</option></select></label><div className="consent-info"><ShieldCheck size={18}/><p>O convite incluirá explicações de privacidade e consentimento. Dados clínicos serão preenchidos somente no ambiente protegido.</p></div></div>:<div className="invite-preview"><div className="avatar avatar-coral">CR</div><h3>Camila Ribeiro</h3><p>Receberá um convite para criar a conta, revisar privacidade e preencher a anamnese selecionada.</p><span>camila.ribeiro@email.com</span></div>}<div className="modal-actions"><button className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary" onClick={()=>step===1?setStep(2):onClose()}>{step===1?"Continuar":"Enviar convite"}<ChevronRight size={17}/></button></div></div></div>;
}

export default function Home() {
  const [surface, setSurface] = useState<Surface>("nutritionist"); const [view, setView] = useState<NutriView>("today"); const [patientStage, setPatientStage] = useState<PatientStage>("list"); const [inviteOpen, setInviteOpen] = useState(false); const [toast, setToast] = useState("");
  const goPatients = () => { setView("patients"); setPatientStage("profile"); };
  const titles: Record<NutriView, [string,string]> = { today: ["Hoje", "Seu consultório em um só lugar"], patients: ["Pacientes", "Cuidado contínuo, sem perder contexto"], consultation: ["Consulta", "Camila Ribeiro · 19 de agosto de 2026"], plan: ["Planos", "Edição e publicação com controle profissional"], growth: ["Crescimento", "Organize sua presença e seus próximos pacientes"] };
  const publish = () => { setToast("Plano versão 2 publicado para Camila"); setTimeout(()=>setToast(""),3500); };
  return <main className="prototype-root"><PrototypeBar surface={surface} onSurface={setSurface}/>{surface==="nutritionist"&&<div className="professional-app"><Sidebar view={view} onChange={(next)=>{setView(next); if(next==="patients") setPatientStage("list")}} /><div className="workspace">{view !== "plan" && <Topbar title={titles[view][0]} subtitle={titles[view][1]} onAddPatient={()=>setInviteOpen(true)} />}<div className={view === "plan" ? "workspace-content builder-content" : "workspace-content"}>{view === "today" && <TodayView onPrepare={()=>setView("consultation")} onPatient={goPatients} onPlan={()=>setView("plan")} onGrowth={()=>setView("growth")} />}{view === "patients" && <PatientsView stage={patientStage} onStage={setPatientStage} onPlan={()=>setView("plan")} />}{view === "consultation" && <ConsultationView onPlan={()=>setView("plan")} />}{view === "plan" && <PlanBuilder onPublish={publish} />}{view === "growth" && <GrowthView />}</div></div></div>}{surface==="patient-web"&&<PatientWeb/>}{surface==="patient-mobile"&&<PatientMobile/>}{surface==="landing"&&<LandingPage/>}{inviteOpen && <InviteModal onClose={()=>setInviteOpen(false)} />}{toast && <div className="toast"><CheckCircle2 size={19}/><span><strong>Plano publicado</strong>{toast}</span></div>}</main>;
}
