/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/public/early-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a professional for founder-led early access */
        post: operations["requestEarlyAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the authenticated user and active organization membership */
        get: operations["getSessionContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a patient only when the authenticated membership has a relationship */
        get: operations["getPatientSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EarlyAccessRequest: {
            name: string;
            /** Format: email */
            email: string;
            currentTool: string;
            source: string;
            marketingConsent: boolean;
            consentTextVersion: string;
        };
        EarlyAccessResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "REGISTERED";
        };
        SessionContext: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /** Format: uuid */
            organizationId: string;
            organizationName: string;
            /** @enum {string} */
            role: "OWNER" | "NUTRITIONIST";
        };
        PatientSummary: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @enum {string} */
            relationshipStatus: "INVITED" | "ACTIVE" | "PAUSED" | "ARCHIVED";
        };
        Problem: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
        };
    };
    responses: {
        /** @description Request failed */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestEarlyAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EarlyAccessRequest"];
            };
        };
        responses: {
            /** @description Interest registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarlyAccessResponse"];
                };
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getSessionContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved session context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getPatientSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-scoped patient summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSummary"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
